model-name: VIT
device: cuda
model:
  batch-size: 512
  ## model input parameters

train:
  epoch: 30
  batch-size: 512
  criterion: 
    name: crossentropyloss
  optimizer:
    name: adam
    args: ## optimizer arguments
      lr: 0.0001
      betas: [0.9, 0.999]
  lr_scheduler:
    name: plateau
    args: ## scheduler arguments
      factor: 0.5
      patient: 10
      mode: min
  log-interval: 10

validate:
  metric: dice

test:
  batch-size: 256
